language: ruby
bundler_args: "--without development"
rvm:
- '2.1'
- '2.0'
- 1.9.3
- jruby
- rbx-2
gemfile:
- gemfiles/Gemfile.rails-4-1
- gemfiles/Gemfile.rails-4-0
- gemfiles/Gemfile.rails-3-2
- gemfiles/Gemfile.rails-3-1
matrix:
  allow_failures:
  - rvm: 2.1.0
  - rvm: rbx-2
