language: ruby
bundler_args: --without development
rvm:
- '2.1'
- '2.0'
- 1.9.3
- jruby
- rbx
gemfile:
- gemfiles/Gemfile.rails-4-1
- gemfiles/Gemfile.rails-4-0
- gemfiles/Gemfile.rails-3-2
services:
- rabbitmq
deploy:
  provider: rubygems
  api_key:
    secure: gNudZK0JaRRweudmkpdkJjUMydItTSW5cXjpYdYCfahqd/cD0xPjxotr2TCHrJibfVauoT/PytbQWcP3jnOYytp6oS0up5Y+uKpGmbqVYx/rZvShWALszcBs71lUh/IZpDXNHc+yo/01HCn10/uQUFRtrjWgMwHtHxXb09xE4wQ=
  gem: acfs
  on:
    branch: master
    repo: jgraichen/acfs
    rvm: 2.1.0
