sudo: false
language: ruby
cache: bundler
bundler_args: "--without development"
rvm:
- '2.2'
- '2.1'
- '2.0'
- 1.9.3
- jruby
gemfile:
- gemfiles/Gemfile.rails-4-2
- gemfiles/Gemfile.rails-4-1
- gemfiles/Gemfile.rails-4-0
- gemfiles/Gemfile.rails-3-2
